name: First Workflow

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Job 1 Step 1
        run: echo "Step 1 complete!"
      - name: Echo Job 1 Step 2
        run: echo "Step 2 complete!"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Job 2 Step 1
        run: echo "This is Job 2, Step 1"
      - name: Cowsays Ready
        uses: peter-evans/cowsay@v1
        with:
          message: "Ready for prod--ship it!"
          color: "magenta"